from datetime import datetime
from sqlalchemy import String, Integer, Float, DateTime, ForeignKey, Text, Boolean
from sqlalchemy.orm import Mapped, mapped_column
from ..db import Base
class User(Base):
    __tablename__="users"; id:Mapped[int]=mapped_column(primary_key=True); email:Mapped[str]=mapped_column(String(255),unique=True,index=True); password_hash:Mapped[str]=mapped_column(String(255)); role:Mapped[str]=mapped_column(String(50),default="Finance Analyst"); active:Mapped[bool]=mapped_column(Boolean,default=True); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class Transaction(Base):
    __tablename__="transactions"; id:Mapped[int]=mapped_column(primary_key=True); transaction_id:Mapped[str]=mapped_column(String(100),unique=True,index=True); date:Mapped[str|None]=mapped_column(String(30),index=True,nullable=True); amount:Mapped[float]=mapped_column(Float); type:Mapped[str]=mapped_column(String(40)); status:Mapped[str]=mapped_column(String(40)); merchant:Mapped[str|None]=mapped_column(String(255)); vendor:Mapped[str|None]=mapped_column(String(255)); settlement_id:Mapped[str|None]=mapped_column(String(100)); settlement_amount:Mapped[float|None]=mapped_column(Float); fee:Mapped[float]=mapped_column(Float,default=0); refund_amount:Mapped[float]=mapped_column(Float,default=0); invoice_id:Mapped[str|None]=mapped_column(String(100)); customer:Mapped[str|None]=mapped_column(String(255)); due_date:Mapped[str|None]=mapped_column(String(30)); payment_status:Mapped[str|None]=mapped_column(String(50)); category:Mapped[str|None]=mapped_column(String(100)); department:Mapped[str|None]=mapped_column(String(100)); currency:Mapped[str]=mapped_column(String(10),default="INR")
class ReconciliationResult(Base):
    __tablename__="reconciliation_results"; id:Mapped[int]=mapped_column(primary_key=True); run_id:Mapped[str|None]=mapped_column(String(40),index=True,nullable=True); transaction_id:Mapped[str]=mapped_column(String(100),index=True); status:Mapped[str]=mapped_column(String(50)); variance:Mapped[float]=mapped_column(Float,default=0); reason:Mapped[str]=mapped_column(Text,default=""); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class Anomaly(Base):
    __tablename__="anomalies"; id:Mapped[int]=mapped_column(primary_key=True); transaction_id:Mapped[str]=mapped_column(String(100),index=True); reason:Mapped[str]=mapped_column(Text); severity:Mapped[str]=mapped_column(String(20)); evidence:Mapped[str]=mapped_column(Text); score:Mapped[float]=mapped_column(Float); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class RiskAssessment(Base):
    __tablename__="risk_assessments"; id:Mapped[int]=mapped_column(primary_key=True); transaction_id:Mapped[str]=mapped_column(String(100),index=True); risk_score:Mapped[float]=mapped_column(Float); risk_level:Mapped[str]=mapped_column(String(20)); risk_factors:Mapped[str]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class AuditLog(Base):
    __tablename__="audit_logs"; id:Mapped[int]=mapped_column(primary_key=True); user_email:Mapped[str]=mapped_column(String(255)); action:Mapped[str]=mapped_column(String(100)); entity:Mapped[str|None]=mapped_column(String(100)); detail:Mapped[str|None]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class ReviewItem(Base):
    __tablename__="review_queue"; id:Mapped[int]=mapped_column(primary_key=True); run_id:Mapped[str|None]=mapped_column(String(40),index=True,nullable=True); transaction_id:Mapped[str]=mapped_column(String(100),index=True); status:Mapped[str]=mapped_column(String(30),default="OPEN"); note:Mapped[str|None]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class ReconciliationRun(Base):
    __tablename__="reconciliation_runs"; id:Mapped[int]=mapped_column(primary_key=True); run_id:Mapped[str]=mapped_column(String(40),unique=True,index=True); mode:Mapped[str]=mapped_column(String(30),default="multi_file"); filename:Mapped[str|None]=mapped_column(String(255)); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow); user_email:Mapped[str]=mapped_column(String(255)); status:Mapped[str]=mapped_column(String(20),default="COMPLETED"); bank_filename:Mapped[str]=mapped_column(String(255)); ledger_filename:Mapped[str]=mapped_column(String(255)); settlement_filename:Mapped[str|None]=mapped_column(String(255)); bank_records:Mapped[int]=mapped_column(Integer,default=0); ledger_records:Mapped[int]=mapped_column(Integer,default=0); settlement_records:Mapped[int]=mapped_column(Integer,default=0); total:Mapped[int]=mapped_column(Integer,default=0); matched:Mapped[int]=mapped_column(Integer,default=0); partial:Mapped[int]=mapped_column(Integer,default=0); unmatched:Mapped[int]=mapped_column(Integer,default=0); duplicate:Mapped[int]=mapped_column(Integer,default=0); exceptions:Mapped[int]=mapped_column(Integer,default=0); match_rate:Mapped[float]=mapped_column(Float,default=0); total_variance:Mapped[float]=mapped_column(Float,default=0)
