FROM python:3.12-slim

WORKDIR /app

COPY backend/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ .

COPY database /database

CMD ["sh","-c","python seed.py && uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}"]
